version: '3'
services:
  backend:
    build:
      context: backend
    ports:
      - 8080:8080
  frontend:
    build:
      context: web
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8080
    ports:
      - 80:3000